### PR TITLE
fix compatibility for webpack

### PR DESCRIPTION
**Pull request by lafin**

### CODE REVIEW

**Comment by vicapow** [comment]
Thanks @lafin!

**Comment by jwerle** [comment]
This PR has introduced an error with my build.

Here is the head of my error output:

```
> browserify app/main.js -o public/js/bundle.js

SyntaxError: Unexpected token (1:10) while parsing file: /Users/jwerle/repos/littlstar/creators/node_modules/webgl-heatmap/vertex-shader-blit.glsl
```

Any ideas/suggestions on how to fix this?

cc @vicapow

**Comment by vicapow** [comment]
@jwerle I can't be sure without seeing an explicit example that demonstrates the behavior but my guess is that you're somehow not applying the `browserify-shader` transform in your build step. The error you posted means browserify is trying to parse the shader code as JS.

**Comment by jwerle** [comment]
@vicapow I'm making use of [react-map-gl-heatmap-overlay](https://github.com/vicapow/react-map-gl-heatmap-overlay) which, until what was made apparent in the issue https://github.com/vicapow/react-map-gl-heatmap-overlay/issues/2, I hasn't been able to build. I see no mention of the need for `browserify-shader` in either project and I've been following both projects.

From intuition, I've tried to apply `browserify-shader` as a transform defined in my `package.json`. Unfortunately, it did not work. In case I'm missing anything, here is what I've defined for browserify transforms:

``` json
"browserify": {
    "transform": [
      "babelify",
      "browserify-shader"
    ]
  }
```

Maybe I'm missing something obvious, but I still have the same error

**Comment by jwerle** [comment]
And for extra reference, a script target in my "scripts" directives for building with browserify is defined as such:

``` json
"build:browser": "browserify app/main.js -o public/js/bundle.js"
```

and I'm using `"browserify": "^13.0.0"`

**Comment by vicapow** [comment]
@jwerle I wasn't able to reproduce with the same command inside of `react-map-gl-heatmap-overlay`. I would `rm -rf node_modules && npm install` to be safe. 

Also, after reading up on browserify transforms, it looks like they only apply to the module code of the project they're defined in so you shouldn't need to additionally apply the browserify-shader transform to your bundle. ref: https://github.com/substack/module-deps#transforms

Apologies I cant be more help :/ Maybe @lafin has any ideas?

**Comment by vicapow** [comment]
@jwerle Also, double check you're using the latest version: https://github.com/vicapow/webgl-heatmap/commit/c2d2233887ff4a35f240dcfc74a40faab5276f80. Should be 0.2.2

**Comment by lafin** [comment]
@jwerle important use browserify-shader with "parameterize": false, but it's not you case

```
"transform": [
      ["browserify-shader", {
        "parameterize": false
      }],
      ...
]
```

Try exclude browserify-shader from you package.json of course if don't needed you.
Try clear modules and make clean npm install.
If it not helped you, make example and I investigate.

**Comment by jwerle** [comment]
@lafin @vicapow Yes the `browserify-shader` transform in my `package.json` is useless and I removed it. I've cleared my node_modules and have tried reinstalling. I have a simple React/Relay/GraphQL application. It appears browserify-shader is not being applied to webgl-heatmap when the glsl files are being required. I'm trying another clean and install now

**Comment by jwerle** [comment]
@lafin @vicapow The issue still persists. I was able to get around it is by using `webgl-heatmap@0.2.0` and `npm-shrinkwrap.json`. Transform are definitely not working. I'm going to make a repo to try to reproduce the error

**Comment by jwerle** [comment]
@lafin @vicapow see https://github.com/jwerle/react-map-gl-heatmap-overlay-webgl-heatmap-browserify-bug for an example setup. Let me know if I'm doing something wrong

**Comment by lafin** [comment]
@jwerle I found problem, but I don't understed, how it happened. 
npm include

```
...
    "transform": [
      "brfs",
      [
        "browserify-shader",
        {
          "parameterize": false
        }
      ]
    ]
...
```

but was pushed 

```
...
    "transform": [
     [
        "browserify-shader",
        {
          "parameterize": false
        }
      ],
      "brfs"
    ]
...
```

now I searching solution...

**Comment by jwerle** [comment]
@lafin Interesting... keep me posted

**Comment by lafin** [comment]
@jwerle Said that it's bug in npm and fixed in npm@3.7.0

**Comment by jwerle** [comment]
@lafin awesome, thanks !

**Pull request merged**
